import {MigrationInterface, QueryRunner} from "typeorm";

export class task2761638451683406 implements MigrationInterface {
    name = 'task2761638451683406'

    public async up(queryRunner: QueryRunner): Promise<void> {
        /*
        Do not use default query generated by typeorm
        Because there is error when try to make the second `migration:run` after `migration:revert`
        Thus, modify query: remove "NOT NULL" condition and add the second query
        that is copying data from "image" column to newly added "imageMobile" column
        */
        //await queryRunner.query(`ALTER TABLE "slides" ADD "imageMobile" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "imageMobile" character varying`);
        await queryRunner.query(`update "slides" set "imageMobile" = "image"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "imageMobile"`);
    }

}
